# -*- coding: utf-8 -*-
"""DS_C2_SC2_LuisGerardoCalvaSilvestre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kbw7ucTc3p_VVaugFcGTIkc1AmodNWUa
"""

#Importamos librerias a utilizar
import pandas as pd
import numpy as np

# a) Extraer informacion del archivo, asegurando el tipo de dato datetime64 para la columna date
country_vaccinations = pd.read_csv('/content/drive/MyDrive/Documents/country_vaccinations.csv', parse_dates=['date'])

# b) Mostrar la estructura y tipos de datos de cada columna
country_vaccinations.info()

# c) Determinar la cantidad de vacunas aplicadas de cada compañía
country_vaccinations[['vaccines','total_vaccinations']].groupby('vaccines').sum()

# d) Obtener la cantidad de vacunas aplicadas en todo el mundo
country_vaccinations['total_vaccinations'].sum()

# e) Calcular el promedio de vacunas aplicadas por país
country_vaccinations[['country','total_vaccinations']].groupby('country').mean()

# f) Determinar la cantidad de vacunas aplicadas el día 29/01/21 en todo el mundo
country_vaccinations.loc[country_vaccinations['date'] == '2021-01-29','total_vaccinations'].sum()

# g)Crear un dataframe nuevo denominado conDiferencias que contenga los datos
# originales y una columna derivada (diferencias) con las diferencias de
# aplicación entre las columnas daily_vaccionations y daily_vaccionations_raw
conDiferencias = country_vaccinations.copy()

#  Se remplazan los valores nulos por ceros para realizar la operacion
conDiferencias['daily_vaccinations_raw'] = conDiferencias['daily_vaccinations_raw'].fillna(0)
conDiferencias['daily_vaccinations'] = conDiferencias['daily_vaccinations'].fillna(0)
conDiferencias['diferencias'] = conDiferencias['daily_vaccinations'] - conDiferencias['daily_vaccinations_raw']
conDiferencias

# h) Obtener el periodo de tiempo entre el registro con fecha más reciente y el
# registro con fecha más antigua
country_vaccinations['date'].max()-country_vaccinations['date'].min()

# i) Crear un dataframe nuevo denominado conCantidad que contenga los datos
# originales y una columna derivada (canVac) con la cantidad de vacunas
# utilizadas cada día (usar la columna vaccines y separar por el carácter , ).
conCantidad = country_vaccinations.copy()
conCantidad['canVac'] = conCantidad['vaccines'].str.split(', ').str.len()
conCantidad

# j) Generar un dataframe denominado antes20 con todos los registros que se
# hayan realizado antes del 20 de diciembre de 2020
antes20 = country_vaccinations.copy()
antes20 = antes20[antes20['date']<"2020-12-20"]
antes20

# k. Obtener un dataframe denominado pfizer con todos los registros donde se
# haya utilizado la vacuna Pfizer
pfizer = country_vaccinations.copy()
pfizer = pfizer[pfizer['vaccines'].str.contains('Pfizer')]
pfizer

# l)Almacenar los dataframes generados (conDiferencias, conCantidad, antes20 y
# pfizer) en un archivo de Excel denominado resultadosReto.xlsx, donde cada
# dataframe ocupe una hoja diferente
with pd.ExcelWriter("/content/drive/MyDrive/Documents/resultadosReto.xlsx") as writer:
    conDiferencias.to_excel(writer, sheet_name="conDiferencias")
    conCantidad.to_excel(writer, sheet_name="conCantidad")
    antes20.to_excel(writer, sheet_name="antes20")
    pfizer.to_excel(writer, sheet_name="pfizer")